from fpdf import FPDF
from PIL import Image, ImageFilter


# 1) Clean prescription PDF (Rajesh) – prescription_rajesh.pdf
def make_clean_prescription_pdf(path="prescription_rajesh.pdf"):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, "Dr. Arun Sharma, MBBS, MD (Internal Medicine)", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, "Reg. No: KA/45678/2015", ln=True)
    pdf.cell(0, 6, "City Medical Centre, 12 MG Road, Bengaluru", ln=True)
    pdf.ln(5)
    pdf.cell(0, 6, "Patient: Rajesh Kumar          Date: 01-Nov-2024", ln=True)
    pdf.cell(0, 6, "Age: 39 years   Gender: M", ln=True)
    pdf.cell(0, 6, "Chief Complaint: Fever since 3 days, body ache", ln=True)
    pdf.ln(5)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 6, "Diagnosis: Viral Fever", ln=True)
    pdf.ln(3)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, "Rx:", ln=True)
    pdf.cell(0, 6, "1. Tab Paracetamol 650mg - 1-1-1 x 5 days", ln=True)
    pdf.cell(0, 6, "2. Tab Vitamin C 500mg - 0-0-1 x 7 days", ln=True)
    pdf.ln(3)
    pdf.cell(0, 6, "Investigations: CBC, Dengue NS1", ln=True)
    pdf.cell(0, 6, "Follow-up: After 5 days if no improvement", ln=True)
    pdf.ln(15)
    pdf.cell(0, 6, "[Doctor's Signature]", ln=True)
    pdf.output(path)


# 2) Clean consultation hospital bill – bill_rajesh.pdf
def make_clean_consultation_bill_pdf(path="bill_rajesh.pdf"):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, "CITY MEDICAL CENTRE", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, "12 MG Road, Bengaluru - 560001", ln=True)
    pdf.cell(0, 6, "GSTIN: 29XXXXX1234X1ZX", ln=True)
    pdf.ln(5)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 6, "BILL / RECEIPT", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, "Bill No: CMC/2024/08321    Date: 01-Nov-2024", ln=True)
    pdf.ln(3)
    pdf.cell(0, 6, "Patient Name: Rajesh Kumar", ln=True)
    pdf.cell(0, 6, "Age/Gender: 39 / Male", ln=True)
    pdf.cell(0, 6, "Referring Doctor: Dr. Arun Sharma", ln=True)
    pdf.ln(5)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(80, 6, "DESCRIPTION", border=1)
    pdf.cell(20, 6, "QTY", border=1)
    pdf.cell(30, 6, "RATE", border=1)
    pdf.cell(30, 6, "AMOUNT", border=1, ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(80, 6, "Consultation Fee (OPD)", border=1)
    pdf.cell(20, 6, "1", border=1)
    pdf.cell(30, 6, "1000.00", border=1)
    pdf.cell(30, 6, "1000.00", border=1, ln=True)
    pdf.cell(80, 6, "CBC (Complete Blood Count)", border=1)
    pdf.cell(20, 6, "1", border=1)
    pdf.cell(30, 6, "200.00", border=1)
    pdf.cell(30, 6, "200.00", border=1, ln=True)
    pdf.cell(80, 6, "Dengue NS1 Antigen Test", border=1)
    pdf.cell(20, 6, "1", border=1)
    pdf.cell(30, 6, "300.00", border=1)
    pdf.cell(30, 6, "300.00", border=1, ln=True)
    pdf.ln(3)
    pdf.cell(0, 6, "Subtotal: 1500.00", ln=True)
    pdf.cell(0, 6, "GST (0% on medical): 0.00", ln=True)
    pdf.cell(0, 6, "Total Amount: 1500.00", ln=True)
    pdf.ln(5)
    pdf.cell(0, 6, "Payment Mode: UPI", ln=True)
    pdf.output(path)


# 3) Pharmacy bill – pharmacy_bill_rajesh.pdf
def make_pharmacy_bill_pdf(path="pharmacy_bill_rajesh.pdf"):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, "HEALTH FIRST PHARMACY", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, "Drug Lic. No: KA-BLR-XXXX", ln=True)
    pdf.cell(0, 6, "22 Brigade Road, Bengaluru", ln=True)
    pdf.ln(5)
    pdf.cell(0, 6, "Bill No: HFP-24-09821    Date: 01-Nov-2024", ln=True)
    pdf.cell(0, 6, "Patient: Rajesh Kumar    Dr: Dr. Arun Sharma", ln=True)
    pdf.ln(5)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(40, 6, "MEDICINE", border=1)
    pdf.cell(25, 6, "BATCH", border=1)
    pdf.cell(25, 6, "EXP", border=1)
    pdf.cell(20, 6, "QTY", border=1)
    pdf.cell(30, 6, "MRP", border=1)
    pdf.cell(30, 6, "AMT", border=1, ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(40, 6, "Paracetamol 650", border=1)
    pdf.cell(25, 6, "A2341", border=1)
    pdf.cell(25, 6, "03/26", border=1)
    pdf.cell(20, 6, "15", border=1)
    pdf.cell(30, 6, "2.50", border=1)
    pdf.cell(30, 6, "37.50", border=1, ln=True)
    pdf.cell(40, 6, "Vitamin C 500", border=1)
    pdf.cell(25, 6, "B7821", border=1)
    pdf.cell(25, 6, "06/26", border=1)
    pdf.cell(20, 6, "10", border=1)
    pdf.cell(30, 6, "4.00", border=1)
    pdf.cell(30, 6, "40.00", border=1, ln=True)
    pdf.ln(3)
    pdf.cell(0, 6, "Subtotal: 77.50", ln=True)
    pdf.cell(0, 6, "Discount (5%): -3.88", ln=True)
    pdf.cell(0, 6, "Net Amount: 73.62", ln=True)
    pdf.output(path)


# 4) Dental bill – dental_bill_priya.pdf
def make_dental_bill_pdf(path="dental_bill_priya.pdf"):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, "SMILE DENTAL CLINIC", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, "Indiranagar, Bengaluru", ln=True)
    pdf.ln(4)
    pdf.cell(0, 6, "Bill No: SDC-24-0451    Date: 15-Oct-2024", ln=True)
    pdf.cell(0, 6, "Patient Name: Priya Singh", ln=True)
    pdf.ln(5)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(80, 6, "DESCRIPTION", border=1)
    pdf.cell(30, 6, "QTY", border=1)
    pdf.cell(30, 6, "RATE", border=1)
    pdf.cell(30, 6, "AMOUNT", border=1, ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(80, 6, "Root Canal Treatment", border=1)
    pdf.cell(30, 6, "1", border=1)
    pdf.cell(30, 6, "8000", border=1)
    pdf.cell(30, 6, "8000", border=1, ln=True)
    pdf.cell(80, 6, "Teeth Whitening (Cosmetic)", border=1)
    pdf.cell(30, 6, "1", border=1)
    pdf.cell(30, 6, "4000", border=1)
    pdf.cell(30, 6, "4000", border=1, ln=True)
    pdf.ln(3)
    pdf.cell(0, 6, "Total Amount: 12000", ln=True)
    pdf.output(path)


# 5) Optional blurry image – needs an existing PNG
from PIL import Image, ImageFilter

def make_blurry(input_path: str, output_path: str, radius: int = 3):
    img = Image.open(input_path)
    # Ensure we are in a mode that supports GaussianBlur
    if img.mode not in ("RGB", "L"):
        img = img.convert("RGB")
    img = img.filter(ImageFilter.GaussianBlur(radius=radius))
    img.save(output_path)

if __name__ == "__main__":
    make_blurry("bill_rajesh-1.png", "prescription_rajesh_blurry.png", radius=3)
    make_blurry("prescription_rajesh-1.png", "bill_rajesh_blurry.png", radius=4)
    make_blurry("pharmacy_bill_rajesh-1.png", "pharmacy_bill_rajesh_blurry.png", radius=4)
    print("Blurred images created.")


# if __name__ == "__main__":
#     make_clean_prescription_pdf("prescription_rajesh.pdf")
#     make_clean_consultation_bill_pdf("bill_rajesh.pdf")
#     make_pharmacy_bill_pdf("pharmacy_bill_rajesh.pdf")
#     make_dental_bill_pdf("dental_bill_priya.pdf")
#     print("Generated: prescription_rajesh.pdf, bill_rajesh.pdf, pharmacy_bill_rajesh.pdf, dental_bill_priya.pdf")